export const DEFAULT_BRAND = [
    {
        brandName: "Nivea",
        brandLogo: "nivea-brand.png",
    }
];
export const DEFAULT_SURVEY = [
    {
        surveyBrandId: 1,
        surveyStartDate: "01-10-2024",
        surveyEndDate: "31-12-2024",
    }
];
export const DEFAULT_PRODUCT = [
    {
        productName: "Skin Firming Body Lotion"
    }
];
export const DEFAULT_RETAIL_CHAIN = [
    {
        retailChain: "Lulu"
    },
    {
        retailChain: "Carrefour"
    },
    {
        retailChain: "AI Madina"
    },
    {
        retailChain: "Nesto"
    },
    {
        retailChain: "Spinneys"
    },
    {
        retailChain: "Almaya"
    },
    {
        retailChain: "Choithrams"
    },
    {
        retailChain: "Life"
    },
    {
        retailChain: "Aster"
    },
    {
        retailChain: "Bin Sina"
    },
    {
        retailChain: "Medicina"
    },
    {
        retailChain: "MedX"
    }
];
export const DEFAULT_STORE_FORMAT = [
    {
        storeFormat: "Hyper"
    },
    {
        storeFormat: "Super"
    },
    {
        storeFormat: "Pharmacy"
    }
];
export const DEFAULT_SKUS = [
    {
        productId: 1,
        skuName: "Skin Firming Nourishing Hydration Body Lotion",
        skuGrammage: "400 ml",
        skuFullName: "Skin Firming Nourishing Hydration 400 ml Body Lotion",
        skuImage: "nourishing-hydration.jpg",
    },
    {
        productId: 1,
        skuName: "Skin Firming Sheer Hydration Body Lotion",
        skuGrammage: "400 ml",
        skuFullName: "Skin Firming Sheer Hydration 400 ml Body Lotion",
        skuImage: "sheer-hydration.jpg",
    },
    {
        productId: 1,
        skuName: "Skin Firming Melanin Beauty and Hydration Body Lotion",
        skuGrammage: "400 ml",
        skuFullName: "Skin Firming Melanin Beauty and Hydration 400 ml Body Lotion",
        skuImage: "melanin-beauty-hydration.jpg",
    }
]
export const DEFAULT_STORES = [
    {
        storeName: "Lulu Karama",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "Karama",
        retailChainId: 1,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Carrefour Marina",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "Marina",
        retailChainId: 2,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Carrefour Barsha",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "Barsha",
        retailChainId: 2,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Carrefour Jumeira",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "Jumeira",
        retailChainId: 2,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Lulu Festival City",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "Festival City",
        retailChainId: 1,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Carrefour AI Ghurair",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "AI Ghurair",
        retailChainId: 2,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "AI Madina AI Qusais",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "AI Qusais",
        retailChainId: 4,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "AI Madina AI Quoz",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "AI Quoz",
        retailChainId: 4,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Lulu Greens",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "Greens",
        retailChainId: 1,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Lulu AI Nahda",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "AI Nahda",
        retailChainId: 1,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Nesto AI Mina",
        storePriority: "High",
        storeFormatId: 1,
        storeArea: "AI Mina",
        retailChainId: 5,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Lulu Supercenter JLT",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "JLT",
        retailChainId: 1,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Spinneys Burdubai",
        storePriority: "High",
        storeFormatId: 2,
        storeArea: "Bur Dubai",
        retailChainId: 6,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Almaya Barsha",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Barsha",
        retailChainId: 7,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Spinneys Central Park",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Sheikh Zayed Rd",
        retailChainId: 6,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Spinneys Marina",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Marina",
        retailChainId: 6,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Almaya Deira City",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Deira",
        retailChainId: 7,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Lulu Supercenter Jebel Ali",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Jebel Ali",
        retailChainId: 1,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Choithrams DIP",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "DIP",
        retailChainId: 8,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Almaya Marina",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Marina",
        retailChainId: 7,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Choithrams Mankhool",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Mankhool",
        retailChainId: 8,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Choithrams Greens",
        storePriority: "Medium",
        storeFormatId: 2,
        storeArea: "Greens",
        retailChainId: 8,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Life Pharmacy Marina View",
        storePriority: "Medium",
        storeFormatId: 3,
        storeArea: "Marina",
        retailChainId: 9,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Aster Pharmacy Dubai Mall",
        storePriority: "High",
        storeFormatId: 3,
        storeArea: "Dubai Mall",
        retailChainId: 10,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "BinSina Pharmacy Barsha",
        storePriority: "Medium",
        storeFormatId: 3,
        storeArea: "Barsha",
        retailChainId: 11,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Medicina Pharmacy Jumeirah",
        storePriority: "High",
        storeFormatId: 3,
        storeArea: "Jumeirah",
        retailChainId: 12,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Aster Pharmacy Bur Dubai",
        storePriority: "Medium",
        storeFormatId: 3,
        storeArea: "Bur Dubai",
        retailChainId: 10,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "LIFE Pharmacy - Karama One",
        storePriority: "Medium",
        storeFormatId: 3,
        storeArea: "Karama",
        retailChainId: 9,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "MedX Pharmacy Sheikh Zayed Road",
        storePriority: "High",
        storeFormatId: 3,
        storeArea: "Sh Zayed Road",
        retailChainId: 13,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "MedX Pharmacy Dubai Mall",
        storePriority: "High",
        storeFormatId: 3,
        storeArea: "Dubai Mall",
        retailChainId: 13,
        storeType: "Mall Based",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "MedX Pharmacy Al Barsha",
        storePriority: "Medium",
        storeFormatId: 3,
        storeArea: "Barsha",
        retailChainId: 13,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Life Pharmacy Greens",
        storePriority: "Medium",
        storeFormatId: 3,
        storeArea: "Greens",
        retailChainId: 9,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    },
    {
        storeName: "Aster Pharmacy Marina",
        storePriority: "Medium",
        storeFormatId: 3,
        storeArea: "Marina",
        retailChainId: 10,
        storeType: "Standalone",
        storeAddress: "",
        storeLocation: ""
    }
]
export const DEFAULT_VISIT = [
    { visitDate: "20-09-2024", surveyId: 1, surveyorId: 1, storeId: 1 },
    { visitDate: "21-09-2024", surveyId: 1, surveyorId: 1, storeId: 2 },
    { visitDate: "22-09-2024", surveyId: 1, surveyorId: 1, storeId: 3 },
    { visitDate: "23-09-2024", surveyId: 1, surveyorId: 1, storeId: 4 },
    { visitDate: "24-09-2024", surveyId: 1, surveyorId: 1, storeId: 5 },
    { visitDate: "25-09-2024", surveyId: 1, surveyorId: 1, storeId: 6 },
    { visitDate: "26-09-2024", surveyId: 1, surveyorId: 1, storeId: 7 },
    { visitDate: "27-09-2024", surveyId: 1, surveyorId: 1, storeId: 8 },
    { visitDate: "28-09-2024", surveyId: 1, surveyorId: 1, storeId: 9 },
    { visitDate: "29-09-2024", surveyId: 1, surveyorId: 1, storeId: 10 },
    { visitDate: "30-09-2024", surveyId: 1, surveyorId: 1, storeId: 11 },
    { visitDate: "01-10-2024", surveyId: 1, surveyorId: 1, storeId: 12 },
    { visitDate: "02-10-2024", surveyId: 1, surveyorId: 1, storeId: 13 },
    { visitDate: "03-10-2024", surveyId: 1, surveyorId: 1, storeId: 14 },
    { visitDate: "04-10-2024", surveyId: 1, surveyorId: 1, storeId: 15 },
    { visitDate: "05-10-2024", surveyId: 1, surveyorId: 1, storeId: 16 },
    { visitDate: "06-10-2024", surveyId: 1, surveyorId: 1, storeId: 17 },
    { visitDate: "07-10-2024", surveyId: 1, surveyorId: 1, storeId: 18 },
    { visitDate: "08-10-2024", surveyId: 1, surveyorId: 1, storeId: 19 },
    { visitDate: "09-10-2024", surveyId: 1, surveyorId: 1, storeId: 20 },
    { visitDate: "10-10-2024", surveyId: 1, surveyorId: 1, storeId: 21 },
    { visitDate: "11-10-2024", surveyId: 1, surveyorId: 1, storeId: 22 },
    { visitDate: "12-10-2024", surveyId: 1, surveyorId: 1, storeId: 23 },
    { visitDate: "13-10-2024", surveyId: 1, surveyorId: 1, storeId: 24 },
    { visitDate: "14-10-2024", surveyId: 1, surveyorId: 1, storeId: 25 },
    { visitDate: "15-10-2024", surveyId: 1, surveyorId: 1, storeId: 26 },
    { visitDate: "16-10-2024", surveyId: 1, surveyorId: 1, storeId: 27 },
    { visitDate: "17-10-2024", surveyId: 1, surveyorId: 1, storeId: 28 },
    { visitDate: "18-10-2024", surveyId: 1, surveyorId: 1, storeId: 29 },
    { visitDate: "19-10-2024", surveyId: 1, surveyorId: 1, storeId: 30 },
    { visitDate: "20-10-2024", surveyId: 1, surveyorId: 1, storeId: 31 },
    { visitDate: "21-10-2024", surveyId: 1, surveyorId: 1, storeId: 32 },
    { visitDate: "22-10-2024", surveyId: 1, surveyorId: 1, storeId: 33 }
];
export const DEFAULT_QUESTIONS = [
    {
        _id: 1,
        questionCategory: "general information",
        questionSubCategory: "instore information",
        questionChildCategory: "display section",
        description: "What is the name of the section (as displayed in the store) where the below products are placed?",
        screenType: "meter-image",
        responseType: "free text"
    },
    {
        _id: 2,
        questionCategory: "general information",
        questionSubCategory: "instore information",
        questionChildCategory: "Overall category size",
        description: "Let's measure the size of the <strong>SKINCARE</strong> category in this store.",
        questionHint:"Measuring tape should be used for the measurements",
        screenType: "meter",
        responseType: "number"
    },
    {
        _id: 3,
        questionCategory: "general information",
        questionSubCategory: "instore information",
        questionChildCategory: "Display alloted",
        description: "Great, Now let's measure the shelf space allocated to the products shown below",
        questionHint:"Measuring tape should be used for the measurements",
        screenType: "meter-image-second",
        responseType: "number"
    },
    {
        _id: 4,
        questionCategory: "Primary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Shelf Availability",
        description: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        screenType: "single-question-yes-no",
        responseType: ""
    },
    {
        _id: 5,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "Primary SKU Facings",
        description: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 6,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "Primary SKU Display",
        description: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 7,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "SKU Unplanned Planogram",
        description: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 8,
        questionCategory: "Primary Visibility",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Shelf Availability",
        description: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        screenType: "single-question-yes-no",
        responseType: ""
    },
    {
        _id: 9,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "Primary SKU Facings",
        description: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 10,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "Primary SKU Display",
        description: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 11,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "SKU Unplanned Planogram",
        description: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 12,
        questionCategory: "Primary Visibility",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Shelf Availability",
        description: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        screenType: "single-question-yes-no",
        responseType: ""
    },
    {
        _id: 13,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "Primary SKU Facings",
        description: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 14,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "Primary SKU Display",
        description: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 15,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Primary Planogram",
        questionChildCategory: "SKU Unplanned Planogram",
        description: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number"
    },
    {
        _id: 16,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Shelf Visibility",
        questionChildCategory: "Wobbler",
        description: "Do you see a <strong>Wobbler</strong> displayed on the shelves in front of you?",
        screenType: "single-question-yes-no",
        responseType: "yes/no"
    },
    {
        _id: 17,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Shelf Visibility",
        questionChildCategory: "Shelf Separator",
        description: "Do you see a <strong>Shelf Separator</strong> displayed on the shelves in front of you?",
        screenType: "single-question-yes-no",
        responseType: "yes/no"
    },
    {
        _id: 18,
        questionCategory: "Primary Visibility",
        questionSubCategory: "Shelf Visibility",
        questionChildCategory: "Shelf Strip",
        description: "Do you see a <strong>Shelf Strip</strong> displayed on the shelves in front of you?",
        screenType: "single-question-yes-no",
        responseType: "yes/no"
    },
    {
        _id: 19,
        questionCategory: "General Information",
        questionSubCategory: "General Information",
        questionChildCategory: "General Information",
        description: "Great JOB !!!<br/>Let's now proceed with the next survey section.",
        screenType: "question-info",
        responseType: ""
    },
    {
        _id: 20,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Count",
        questionChildCategory: "Gondola Count",
        description: "Pls walk around various sections and proceed once you have seen any of sections displayed in the below images.",
        screenType: "gondola-fsu-selection",
        responseType: ""
    },
    {
        _id: 21,
        questionCategory: "General Information",
        questionSubCategory: "General Information",
        questionChildCategory: "General Information",
        description: "OK,<br/>Let's start with the survey of <strong>Gondola End</strong>.",
        screenType: "question-info",
        responseType: "selection",
        placeArea: "gondola",
    },
    {
        _id: 22,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola End",
        questionChildCategory: "Gondola Location",
        description: "Please provide the name of section where this <strong>Gondola End</strong> is kept in the store.",
        screenType: "meter-image",
        responseType: "free text",
        placeArea: "gondola",
    },
    {
        _id: 23,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Branding",
        questionChildCategory: "Gondola Branding",
        description: "Is the branding on the <strong>Gondola</strong> same as the one displayed in the below picture?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 24,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Gondola SKU Availability",
        description: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 25,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Facings",
        description: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "gondola",
    },
    {
        _id: 26,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Display",
        description: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 27,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Gondola SKU Availability",
        description: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 28,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Facings",
        description: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "gondola",
    },
    {
        _id: 29,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Display",
        description: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 30,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Gondola SKU Availability",
        description: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the Gondola End?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 31,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Facings",
        description: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "gondola",
    },
    {
        _id: 32,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Display",
        description: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 33,
        questionCategory: "General Information",
        questionSubCategory: "General Information",
        questionChildCategory: "General Information",
        description: "Great going !!!<br/>Let's now move to the next <strong>Gondola End</strong> kept in the store.",
        screenType: "question-info",
        responseType: "free text",
        placeArea: "gondola",
    },
    {
        _id: 34,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola End",
        questionChildCategory: "Gondola Location",
        description: "Please provide the name of section where this <strong>Gondola End</strong> is kept in the store.",
        screenType: "meter-image",
        responseType: "free text",
        placeArea: "gondola",
    },
    {
        _id: 35,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Branding",
        questionChildCategory: "Gondola Branding",
        description: "Is the branding on the <strong>Gondola</strong> same as the one displayed in the below picture?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 36,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Gondola SKU Availability",
        description: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 37,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Facings",
        description: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "gondola",
    },
    {
        _id: 38,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Display",
        description: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 39,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Gondola SKU Availability",
        description: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 40,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Facings",
        description: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "gondola",
    },
    {
        _id: 41,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Display",
        description: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 42,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "Gondola SKU Availability",
        description: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the Gondola End?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 43,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Facings",
        description: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "gondola",
    },
    {
        _id: 44,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "Gondola Planogram",
        questionChildCategory: "Gondola SKU Display",
        description: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "gondola",
    },
    {
        _id: 45,
        questionCategory: "General Information",
        questionSubCategory: "General Information",
        questionChildCategory: "General Information",
        description: "Great JOB !!!<br/>Let's now proceed with the survey of the <strong>FSUs</strong> or <strong>Free Standing Units</strong> placed in the store as shown in the image below.",
        shortQuestion: "Pls walk around various sections and proceed once you have seen a FSU",
        screenType: "question-info",
        responseType: "free text",
        placeArea: "fsu",
    },
    {
        _id: 46,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Count",
        questionChildCategory: "FSU Count",
        description: "How many <strong>FSUs</strong> as displayed in the Image below did you see in the store?",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "fsu",
    },
    {
        _id: 47,
        questionCategory: "General Information",
        questionSubCategory: "General Information",
        questionChildCategory: "General Information",
        description: "OK,<br/>Let's start with the survey of the first <strong>FSUs</strong>",
        screenType: "question-info",
        responseType: "free text",
        placeArea: "fsu",
    },
    {
        _id: 48,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU",
        questionChildCategory: "FSU Location",
        description: "Please provide the name of section where this <strong>FSU</strong> is kept in the store.",
        screenType: "meter-image",
        responseType: "free text",
        placeArea: "fsu",
    },
    {
        _id: 49,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Branding",
        questionChildCategory: "FSU Branding",
        description: "Is the branding on the <strong>FSU</strong> same as the one displayed in the below picture?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 50,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "FSU SKU Availability",
        description: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 51,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Facings",
        description: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "fsu",
    },
    {
        _id: 52,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Display",
        description: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 53,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "FSU SKU Availability",
        description: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 54,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Facings",
        description: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "fsu",
    },
    {
        _id: 55,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Display",
        description: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 56,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "FSU SKU Availability",
        description: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the FSU?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 57,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Facings",
        description: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "fsu",
    },
    {
        _id: 58,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Display",
        description: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 59,
        questionCategory: "General Information",
        questionSubCategory: "General Information",
        questionChildCategory: "General Information",
        description: "Great going !!!<br/>Let's now move to the next <strong>FSU</strong> kept in the store.",
        screenType: "question-info",
        responseType: "free text",
        placeArea: "fsu",
    },
    {
        _id: 60,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU",
        questionChildCategory: "FSU Location",
        description: "Please provide the name of section where this <strong>FSU</strong> is kept in the store.",
        screenType: "question-info",
        responseType: "free text",
        placeArea: "fsu",
    },
    {
        _id: 61,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Branding",
        questionChildCategory: "FSU Branding",
        description: "Is the branding on the <strong>FSU</strong> same as the one displayed in the below picture?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 62,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "FSU SKU Availability",
        description: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 63,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Facings",
        description: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "fsu",
    },
    {
        _id: 64,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Display",
        description: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 65,
        questionCategory: "Secondary Availability",
        questionSubCategory: "SKU Availability",
        questionChildCategory: "FSU SKU Availability",
        description: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 66,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Facings",
        description: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "fsu",
    },
    {
        _id: 67,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Display",
        description: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 68,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "SKU availability",
        questionChildCategory: "FSU SKU availability",
        description: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the FSU?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
    {
        _id: 69,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Facings",
        description: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        questionHint:"Facings are the number of units of the SKUs displayed on the front row \nDo not count units kept in the back rows",
        screenType: "meter-count",
        responseType: "number",
        placeArea: "fsu",
    },
    {
        _id: 70,
        questionCategory: "Secondary Visibility",
        questionSubCategory: "FSU Planogram",
        questionChildCategory: "FSU SKU Display",
        description: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        screenType: "single-question-yes-no",
        responseType: "yes/no",
        placeArea: "fsu",
    },
]
export const DEFAULT_SURVEY_QUESTIONS=[
  {
    questionId: 1,
    brandId: 1,
    productId: 1,
    skuId: 1,
    visitId: 1,
    expectedResponse:"",
    surveyorResponse:"",
    baseScore: 0,
    referenceImage:"",
    surveyorImage:""
  }
]